# Generated by Django 5.0.1 on 2024-06-03 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegisteredCustomer",
            fields=[
                ("c_id", models.IntegerField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(max_length=100)),
                ("c_add", models.CharField(max_length=255)),
                ("mob_no", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="TransportOffice",
            fields=[
                ("point_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("time", models.TimeField()),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Taxi",
            fields=[
                ("t_id", models.IntegerField(primary_key=True, serialize=False)),
                ("type", models.CharField(max_length=50)),
                ("capacity", models.IntegerField()),
                ("cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.registeredcustomer",
                    ),
                ),
                (
                    "point_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transportoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RouteDetails",
            fields=[
                ("r_no", models.IntegerField(primary_key=True, serialize=False)),
                ("src", models.CharField(max_length=255)),
                ("dest", models.CharField(max_length=255)),
                (
                    "point_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transportoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("src", models.CharField(max_length=255)),
                ("dest", models.CharField(max_length=255)),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.registeredcustomer",
                    ),
                ),
                (
                    "point_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transportoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "t_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.taxi"
                    ),
                ),
                (
                    "point_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transportoffice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaseStation",
            fields=[
                ("b_id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("loc", models.CharField(max_length=255)),
                ("src", models.CharField(max_length=255)),
                ("dest", models.CharField(max_length=255)),
                (
                    "point_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transportoffice",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                fields=("point_id", "t_id"), name="unique_registration"
            ),
        ),
    ]
